### ISSUE TITLE
Create a 'brew' formula to install kapp

### ISSUE THREAD

**Issue by peterj** [peterj/kapp#2]
At the moment, you need to manually download the binary. It would be nice if users could do `brew install kapp` to install the tool

**Comment by jmhobbs** [comment]
I'd like to do this, but I'm concerned it wouldn't qualify for the Acceptable Formulae rules: 
 https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md.

For instance kapp does not appear to "have a homepage" which is a requirement.

That said, would you be open to maintaining a tap?  That would require a second repo `homebrew-kapp` and a handful of files in there.  Then folks could `brew install peterj/kapp/kapp` or `brew tap peterj/kapp && brew install kapp`

**Comment by jmhobbs** [comment]
Nope, not really.  If you create a `homebrew-kapp` repo on Github I can PR against it and be up and running right away.

**Comment by peterj** [comment]
Perfect - I created the repo! Will open an issue there and tag it with
`hactoberfest`, so you get the credit.
