### ISSUE TITLE
Replace semver.xyz references for bumping versions

### ISSUE THREAD

**Issue by peterj** [peterj/kapp#6]
Semver.xyz is down and tbh it was a bad idea to rely on it, instead we should create/use another solution to bump the version. Semver is currently used [here](https://github.com/peterj/kapp/blob/83fd065986b5e4a3e2c53756a634bc8051200d4d/internal/artifacts/golang/templates/templates.go#L62) and in the main Makefile as well. 

If this could be done in Makefile itself - perfect - if not, using another Go package or something to bump the version would be great as well.

**Comment by peterj** [comment]
@Mave95 feel free to assign this to yourself.

**Comment by Mave95** [comment]
I've also replaced the code in the templates.go. Thanks for the reminder of this issue.

**Comment by peterj** [comment]
Thanks for fixing this @Mave95. 
Fixed by #7
